### ISSUE TITLE
Rotate between USD, sats, BTC and hidden state when tapping balance

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/blink-mobile#1779]
Some LN wallets rotate between sats, BTC and fiat units when tapping the balance. BBW only hides the balance. 
I think it would be helpful both from UX side and educational side, to have similar functionality. Gives user choice and teaches newcommers to understand relation between sats to BTC to fiat, get intuition about the current prices and makes them understand there is no fiat in the wallet, only bitcoin. You do this well in chart by displaying price of 100k sats. 
I think balance units could rotate between sats, fiat, (maybe BTC) and hidden.

**Comment by UncleSamtoshi** [comment]
Are you referring to just the main wallet balance? I'm not sure if it makes sense to be able to show the main balance in anything other than the display currency because it is a combination of both stablesats (usd) and normal satoshis.

**Comment by designsats** [comment]
ok, closing.
