### ISSUE TITLE
Failed to calculate fee when sending from Stablesats account onchain

### ISSUE THREAD

**Issue by designsats** [GaloyMoney/blink-mobile#2800]
- only observed from Stablesats

![image](https://github.com/GaloyMoney/galoy-mobile/assets/17384787/7d40f04b-5c41-496d-b161-1cf45a587caf)

**Comment by nicolasburtey** [comment]
did you tried to send the full amount? any different behavior with a different/lower amount?

**Comment by sandipndev** [comment]
I am facing the same issue when sending a small payment. Opening up some discussion around this screen.

1. We should never really say "Failed to calculate fee".
2. If we can't really send an onchain payment for such a low sats amount, then we shouldn't allow confirming of the payment.
3. We should perhaps show by a % split graph of how much the user is sending onchain and how much fees they will pay?

**Comment by designsats** [comment]
Ive $69 in stables and getting the error attempting $50 onchain tx.
Any amount. 

Possibly a color alert too? 
![dark theme - send onchain - step2](https://github.com/GaloyMoney/galoy-mobile/assets/17384787/75f2bf06-425c-4a6c-8093-9a5a3c243c86)

**Comment by designsats** [comment]
no longer happening, closing
