### ISSUE TITLE
Lightning invoice don't populate

### ISSUE THREAD

**Issue by ThinusXpressed** [GaloyMoney/blink-mobile#3058]
**Describe the bug**
Blink send flow but it doesn't populate the Lightning invoice to pay from cryptoqr / bitrefill

**To Reproduce**
_**Bitrefill**_
1. Select voucher on Bitrefill
2. Checkout
3. Select Pay with Lightning
4. Select wallet: Blink
5. Select Open in Blink
6. Blink opens up on send screen but the invoice did not populate

_**Crypto QR**_
1. Select wallet: Blink
2. Select Test Wallet
3. Blink opens up on send screen but the test invoice did not populate

**Expected behavior**
The wallet must open and populate the incoice to be paid.

**Screenshots**
[Video 1](https://drive.google.com/file/d/1D1ehawLdiQU-_odoV_CVoXJheuCP-egp/view?usp=sharing)
[Video 2](https://drive.google.com/file/d/1ts6ITtB2I3UOpwS2WHwexXUdMw3Keyu3/view?usp=sharing) 

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A05
- OS: Android
- Version Android version 13

**Additional context**

**Comment by nicolasburtey** [comment]
That should be fixed with the last version, currently in beta (accessible through TestFlight or downloadable from GitHub)

This will probably be rolled out publicly next week
