### ISSUE TITLE
bitcoin: what is it?

### ISSUE THREAD

**Issue by nicolasburtey** [GaloyMoney/blink-mobile#3217]
when in "explore wallet" mode, going to earn/"bitcoin what is it?" leads to the a blue screen with no information

<img width="346" alt="image" src="https://github.com/GaloyMoney/galoy-mobile/assets/11156370/228d4789-ab0d-44d1-afaf-2cb482cd3175">

**Comment by royalpinto007** [comment]
Hi @nicolasburtey,
I would like to take this issue. Could you please provide details on the content we are considering adding here? 
Also, it appears that this is the first lesson in the Earn section & work on all the lessons needs to be done. I am ready to take on all of them if I am given some hints.

**Comment by royalpinto007** [comment]
Update- I downloaded the Blink app from the app store to check if it's the same, and I found that we already have the content. It seems like it's hidden for some reason, only in the development environment.

![blink-app-lessons](https://github.com/GaloyMoney/galoy-mobile/assets/97520428/fe9e1506-8a37-493d-8cae-84ff3a44642b)
