### ISSUE TITLE
Incorrect Pluralization in Earn Section

### ISSUE THREAD

**Issue by royalpinto007** [GaloyMoney/blink-mobile#3229]
**Describe the bug**
In the earn section, when 1 sat is earned, it incorrectly displays "1 sats" instead of "1 sat".

**To Reproduce**
1. Navigate to the earn section.
2. Perform an action that earns 1 sat.
3. Observe the display message.

**Expected behavior**
When 1 sat is earned, the display message should correctly show "1 sat".

**Similar Issue:**
This issue is similar to the notifications pluralization problem reported in the issue https://github.com/GaloyMoney/galoy-mobile/issues/3171.

**Screenshots**
![1sat-earn](https://github.com/GaloyMoney/galoy-mobile/assets/97520428/4f2983c2-91be-4344-b651-81f3f91b85a4)

**Comment by nicolasburtey** [comment]
@Prakhar-Agarwal-byte
