### ISSUE TITLE
Inconsistent interaction in NumberPad

### ISSUE THREAD

**Issue by shivamgupta2020** [GaloyMoney/blink-mobile#3244]
**Describe the bug**
In the Blink Android app, the number pad to enter numbers shows clicks only on the number but not the button. Secondly, I have manually clicked to clear a number one by one; the Clear Hold button to clear whole text functionality is not working. 

**To Reproduce**
1. Open Convert
2. Click on Set Amount
3. click on numbers

**Expected behavior**
On Clicking on any number, the whole tile should show a different shade instead of only the number.
When holding the clear button, all text should be cleared.
**Screenshots**

https://github.com/GaloyMoney/blink-mobile/assets/91847638/7d2447ff-4a3b-40aa-863a-97c883f682ad

**Smartphone (please complete the following information):**

- Device: Realme GT2
- OS: Android 14

**Comment by nicolasburtey** [comment]
@Prakhar-Agarwal-byte
