### ISSUE TITLE
Camera Stretched the Image

### ISSUE THREAD

**Issue by ThinusXpressed** [GaloyMoney/blink-mobile#3256]
**Describe the bug**
When I want to scan a QR the camera stretched the image from side-to-side.

**To Reproduce**

1. Open Blink
2. Tap on Scan
3. Hover the camera over QR code

**Expected behavior**
The camera should show the image in proportion and the square shape QR should fit in the sqaure shape block in the screen.

**Screenshots**
![WhatsApp Image 2024-05-08 at 10 50 18_e94d6c90](https://github.com/GaloyMoney/blink-mobile/assets/121315637/cebe86d5-8312-42d7-9b8c-4249faa1fdc1)

https://github.com/GaloyMoney/blink-mobile/assets/121315637/41639f0e-48ed-4968-a217-f4799c110902

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A05
- OS: Android
- Version: 14

**Additional context**

**Comment by nicolasburtey** [comment]
is this issue still present with the last version @ThinusXpressed ?

**Comment by ThinusXpressed** [comment]
@nicolasburtey , the camera is now working fine, thanks!
