### ISSUE TITLE
June Blink Circles Challenge

### ISSUE THREAD

**Issue by rudyblink** [GaloyMoney/blink-mobile#3260]
New content for modal
--ENGLISH--

Win a privilege ticket to Adopting Bitcoin El Salvador 

Expand your Inner Circle by 10 for a chance to win a $1000 privilege ticket to Adopting Bitcoin El Salvador! The ticket includes exclusive access to the main conference, mezzanine with food/drinks/snacks, speakers' dinner, and the Film Festival. 

This time, there will be two winners!

Share your circles on social with the hashtag #blinkcircles to participate. 

Learn more about Adopting Bitcoin at https://sv24.adoptingbitcoin.org/ 

--SPANISH--

Gana un boleto privilegio para Adopting Bitcoin El Salvador

¡Amplía tu Círculo Interno en 10 para tener la oportunidad de ganar un boleto privilegio de $1000 para Adopting Bitcoin El Salvador! El boleto incluye acceso exclusivo a la conferencia principal, al entrepiso con comida/bebidas/snacks, a la cena de los oradores y al Festival de Cine. 

¡Esta vez, habrá dos ganadores!

Comparte tus círculos en las redes sociales con el hashtag #blinkcircles para participar.

Obtén más información sobre Adopting Bitcoin en https://sv24.adoptingbitcoin.org/

--ENGLISH--

June Challenge!

Expand your Inner Circle by 10 for a chance to win a $1000 privilege ticket to the Adopting Bitcoin El Salvador

--SPANISH--

Challenge de Junio!

¡Amplía tu Círculo Interno en 10 para tener la oportunidad de ganar un boleto privilegio de $1000 para Adopting Bitcoin El Salvador!

![June Challenge](https://github.com/GaloyMoney/blink-mobile/assets/156244225/34bdf2e6-762c-474f-8c28-8bf4bbfaebf1)

**Comment by nicolasburtey** [comment]
@Prakhar-Agarwal-byte
